### ISSUE TITLE
(Feature Request) 

### ISSUE THREAD

**Issue by Cloudre** [kazemcodes/IReader#11]
Is it possible to add an option to follow the device's brightness. It is quite painful to the eyes, when you open a novel in a not well lit room. Thank you

**Comment by kazemcodes** [comment]
for now, you can change the brightness in reader screen settings, I will add this setting to follow users brightness later

**Comment by Cloudre** [comment]
> for now, you can change the brightness in reader screen settings, I will add this setting to follow users brightness later
.

Ok Thank You👍
