### ISSUE TITLE
App crashing when scrolling

### ISSUE THREAD

**Issue by Cloudre** [kazemcodes/IReader#15]
**Describe the bug**
I was readingvThe demon prince goes to the academy from source mylovenovel. While looking for the part i was at on ch. 91. The app suddenly chrashed, it keeps on happening when i scroll really fast. 

**To Reproduce**
1. Go to 'The demon Prince goes to the Academy'
2. Click on 'On continue Reading'
3. Scroll down to 'Any part really fast'

**Expected behavior**
It is expected that when you scroll to fast the app logo either appears then exit to home screen or just immedietely exits.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [Huawei Y6p]
 - OS: [Emui 10]

**Additional context**
I hadn't tried it on other novels s yet as i just recently updated the app and forgot to back up. I will post the video on discord.

**Comment by Cloudre** [comment]
@

Uploading SVID_20220410_230945_1.mp4…

**Comment by Cloudre** [comment]
Uploading SVID_20220410_221610_1.mp4…

**Comment by Cloudre** [comment]
As it seems I can't upload the video on discord and here, I would just send this link instead.

https://youtube.com/shorts/RIYvLYC2UJw?feature=share

**Comment by kazemcodes** [comment]
thanks for reporting
