### ISSUE TITLE
Add continues reading option in cover of the novel

### ISSUE THREAD

**Issue by EclairEcleirEicler** [kazemcodes/IReader#3]
![IMG_20220202_164025](https://user-images.githubusercontent.com/96762106/152140346-74e2a79b-4778-4e0e-b3f6-1725338e9448.jpg)

Add this option in the cover of novel

Feature name - continues reading
Feature function - if we click in the "continue reading" option in novel cover it's will automatically open the last read chapter or if we start a new novel it's will Start the 1st chapter of novel

Reference - tachiyomi j2k

**Comment by kazemcodes** [comment]
Thank you for suggesting this feature, I Already added this feature to the app, wait for next update.
