### ISSUE TITLE
Chapter starting at the bottom. 

### ISSUE THREAD

**Issue by Cloudre** [kazemcodes/IReader#4]
**Describe the bug**
According to the user, whenever he go to the next chapter, it start at the bottom instead of the beginning part of the chapter. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I didn't experience it first hand, but  itried to reproduce the bug, but for me instead of starting at the bottom, it would a start few lines bellow the beginning of the chapter.

**Comment by kazemcodes** [comment]
I fix this bug, wait for next update,
thanks a lot for reporting this issue
